name: torrid
description: "Ronin 安卓端：打卡/随笔/漫画/画廊等多功能自用应用。"


version: 1.0.0+1

environment:
  sdk: ^3.8.1

# 应用依赖
dependencies:
  flutter:
    sdk: flutter

  # ----运行依赖----
  # 状态管理riverpod
  flutter_riverpod: ^2.3.0
  riverpod_annotation: ^2.3.0
  # 数据持久化方案. Hive, shared_preferences, sqflite
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.3.2
  sqflite: ^2.4.1
  # 路径获取及处理.
  path_provider: ^2.1.5
  path: ^1.9.1
  # 路由管理
  go_router: ^16.1.0
  # 权限管理
  permission_handler: ^12.0.1
  # id生成
  uuid: ^4.5.2


  # ----网络----
  # 更强大的网络请求.
  dio: ^5.9.0


  # ----更好的显示----
  # 时间格式化
  intl: ^0.20.2
  # 拼音排序支持
  pinyin: ^3.3.0
  # markdown渲染
  flutter_markdown_plus: ^1.0.5
  # 日志logging
  logging: ^1.3.0


  # ----媒体文件相关----
  # 视频播放
  chewie: ^1.12.1
  video_player: ^2.10.0
  # 本地图片选择
  image_picker: ^1.2.0
  # 查看图片
  photo_view: ^0.15.0
  # 图片处理库
  image_size_getter: ^2.4.1
  # 图片的网络缓存
  cached_network_image: ^3.4.1
  # 图像处理库
  image: ^4.5.4

  # 链接跳转
  url_launcher: ^6.3.0


  # ----codegen代码生成----
  json_annotation: ^4.9.0
  # mDNS 服务发现
  multicast_dns: ^0.3.3
  # 图片缓存管理
  flutter_cache_manager: ^3.4.1
  

# 开发时插件-------:
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
  # 代码生成.
  build_runner: ^2.4.13
  hive_generator: ^2.0.1
  riverpod_generator: ^2.3.9
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/cert/
  fonts:
    # 楷体  自然美感, 适合小段落,副标题.
    - family: kaiti
      fonts:
        - asset: assets/fonts/kaiti.ttf
    # iconfont
    - family: iconfont
      fonts:
        - asset: assets/fonts/iconfont.ttf

